Setup GNUStep caching
After ~70 workflow runs and _many_ hours, I finally figured out a solution that works... Damn I hate creating workflow files

diff --git a/.github/workflows/gnustep.yml b/.github/workflows/gnustep.yml
--- a/.github/workflows/gnustep.yml
+++ b/.github/workflows/gnustep.yml
@@ -1,6 +1,8 @@
 name: GNUStep
 
 on:
+  push:
+    branches: [master]
   pull_request:
 
 env:
@@ -20,6 +22,71 @@ jobs:
     steps:
     - uses: actions/checkout@v2
 
+    - name: Install Clang
+      run: sudo apt-get install clang
+
+    - name: Cache GNUStep
+      id: cache-gnustep
+      uses: actions/cache@v2
+      with:
+        # Ideally I would have just cached build-files, and then rerun make
+        # every time, letting it figure out what's changed. But GNUStep-Base
+        # ./configure invalidates the cache, which makes it very hard to
+        # know when to rebuild and when not to.
+        # So instead we just cache the final output:
+        # - lib/libobjc.so
+        # - lib/libgnustep-base.so
+        # - include/Foundation/*
+        # - include/objc/*
+        # - ...
+        path: |
+          ~/gnustep/lib
+          ~/gnustep/include
+        key: gnustep-libobjc2_1.9-make_2.9.0-base_1.28.0
+
+    - name: Setup environment
+      run: |
+        mkdir -p $HOME/gnustep
+        echo "PATH=$HOME/gnustep/bin:$PATH" >> $GITHUB_ENV
+        echo "LIBRARY_PATH=$HOME/gnustep/lib:$LIBRARY_PATH" >> $GITHUB_ENV
+        echo "LD_LIBRARY_PATH=$HOME/gnustep/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
+        echo "CPATH=$HOME/gnustep/include:$CPATH" >> $GITHUB_ENV
+        ls -al ~/gnustep/* || true # Ignore failures
+
+    - name: Install Make
+      if: steps.cache-gnustep.outputs.cache-hit != 'true'
+      run: sudo apt-get install make
+
+    - name: Install GNUStep libobjc2
+      if: steps.cache-gnustep.outputs.cache-hit != 'true'
+      run: |
+        wget https://github.com/gnustep/libobjc2/archive/refs/tags/v1.9.tar.gz
+        tar -xzf v1.9.tar.gz
+        mkdir -p libobjc2-1.9/build
+        cd libobjc2-1.9/build
+        cmake -Wno-dev -DCMAKE_INSTALL_PREFIX=$HOME/gnustep -DTESTS=OFF ..
+        make install
+
+    - name: Install GNUStep make
+      if: steps.cache-gnustep.outputs.cache-hit != 'true'
+      run: |
+        wget https://github.com/gnustep/tools-make/archive/refs/tags/make-2_9_0.tar.gz
+        tar -xzf make-2_9_0.tar.gz
+        mkdir -p tools-make-make-2_9_0/build
+        cd tools-make-make-2_9_0/build
+        ../configure --prefix=$HOME/gnustep --with-library-combo=ng-gnu-gnu
+        make install
+
+    - name: Install GNUStep-Base
+      if: steps.cache-gnustep.outputs.cache-hit != 'true'
+      run: |
+        wget https://github.com/gnustep/libs-base/archive/refs/tags/base-1_28_0.tar.gz
+        tar -xzf base-1_28_0.tar.gz
+        cd libs-base-base-1_28_0
+        ./configure --prefix=$HOME/gnustep --disable-tls --disable-xslt
+        make install
+        ls -al $HOME/gnustep/*
+
     - name: Cache Rust
       uses: actions/cache@v2
       with:
@@ -30,48 +97,11 @@ jobs:
         restore-keys: |
           gnustep-cargo-
 
-    - name: Install Packages
-      run: sudo apt-get install gobjc clang make libblocksruntime-dev
-
-    - # Run before we install GNUStep as a "fail fast" mechanism
-      name: Run checks
+    - name: Run checks
       uses: actions-rs/cargo@v1
       with:
         command: check
         args: --verbose --no-default-features
-
-    - name: Install GNUStep libobjc2
-      run: |
-        wget https://github.com/gnustep/libobjc2/archive/refs/tags/v1.9.tar.gz
-        tar -xzf v1.9.tar.gz
-        mkdir -p libobjc2-1.9/build
-        cd libobjc2-1.9/build
-        cmake ../
-        sudo make install
-
-    - name: Install GNUStep make
-      run: |
-        wget https://github.com/gnustep/tools-make/archive/refs/tags/make-2_9_0.tar.gz
-        tar -xzf make-2_9_0.tar.gz
-        cd tools-make-make-2_9_0
-        ./configure --with-library-combo=ng-gnu-gnu
-        sudo make install
-
-    - name: Install GNUStep-Base
-      run: |
-        wget https://github.com/gnustep/libs-base/archive/refs/tags/base-1_28_0.tar.gz
-        tar -xzf base-1_28_0.tar.gz
-        cd libs-base-base-1_28_0
-        ./configure --disable-tls
-        sudo make install
-
-    - name: Setup environment
-      run: |
-        ls -al /usr/local/lib
-        ls -al /usr/local/include
-        echo "LIBRARY_PATH=/usr/local/lib:$LIBRARY_PATH" >> $GITHUB_ENV
-        echo "LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
-        echo "CPATH=/usr/local/include:$CPATH" >> $GITHUB_ENV
 
     - name: Test GNUStep
       uses: actions-rs/cargo@v1
